import Head from "next/Head"
import estilos from "@/estilos/Home.module.css"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=l"/>
                <Link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}